### Задание 1
#### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [120]:
import numpy as np
N = int(input('Введите N: '))
mas = np.arange(0, N)
print(sorted(mas, reverse = True))

Введите N: 10
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


### Задание 2
#### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [122]:
def diag_sum(N):
    total_sum = 0
    mass = np.arange(0, N)
    mass_res = (sorted(mass, reverse = True))
    matrix = np.diag(mass_res)
    print(matrix)
    for row in range(len(matrix)):
        total_sum += matrix[row][row]
    return total_sum
diag_sum(5)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


10

### Задание 3
#### Решите систему уравнений:
#### 4x + 2y + z = 4
#### x + 3y = 12
#### 5y + 4z = -3

In [33]:
from numpy import linalg
left = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
right = np.array([4, 12, -3])
print(f"X = {linalg.solve(left, right)[0]}, Y = {linalg.solve(left, right)[1]}, Z = {linalg.solve(left, right)[2]}")

X = 0.4666666666666668, Y = 3.844444444444444, Z = -5.555555555555555
